### ISSUE TITLE
[FEAT REQUEST] Add an example of a route using proxy authenticated proxy route

### ISSUE THREAD

**Issue by blanklob** [Shopify/shopify-app-template-remix#295]
Would be really appreciated to provide an example route (or documentation for developers) for integrating a proxy route `app/proxy` that can be queried from an online store channel.

-- Idea --

A good example would include a simple authenticated fetch request to update customer data from a theme app extension or a metafield ressource on the customer that is created by the app from an app block.

**Comment by sam-masscreations** [comment]
+1

**Comment by byrichardpowell** [comment]
Thanks for opening this issue.

We think this is something we missed but we want to make it as easy as possible. We think we'll add a new API to authenticate requests from a storefront context.

To help us design this, please can you confirm that you are referring to App proxy requests from a storefront: https://shopify.dev/docs/apps/online-store/app-proxies

If you can, we'll make this a priority.

**Comment by blanklob** [comment]
Yes that will be so cool.

And yes Im talking about those app proxies.

**Comment by byrichardpowell** [comment]
Hi @pkyek1 I am hoping to prioritize it after the [unauthenticated admin client](https://github.com/Shopify/shopify-app-js/pull/407) ships, which seems to be affecting more people right now.

**Comment by ericnkatz** [comment]
Excited to see this making progress! Thanks @byrichardpowell!

**Comment by simone-boa-ideas** [comment]
That would be really cool to have :) I'm also trying to figure out how to make a proxy route with remix
Thank you @byrichardpowell

**Comment by sam-masscreations** [comment]
@byrichardpowell Thanks for getting back so quickly! Really appreciate your fast turn around of the Remix changes! 

My use case I need to create discount codes using a third party loyalty points system.
I have an app block which will get available points. I need the request to get the current logged in customer to make sure points are available in the third party DB. If available, then i will create a Discount code and send back to the front end

**Comment by huykon** [comment]
Hi @byrichardpowell Thank for you & team for the fast development.
I upgraded the library to v1.1.0 & trying to define the authentication public. The error happening is 
**Property 'storefrontAppProxy' does not exist on type 'AuthenticatePublic'**
What should I do at the moment?
![image](https://github.com/Shopify/shopify-app-template-remix/assets/9253798/399e20e5-0015-4435-8713-5551d7938256)

**Comment by byrichardpowell** [comment]
Thanks @sam-masscreations .  That makes sense.

@huykon Are you able to achieve what you need using the admin API? We think we should return a storefront API client, but that might take us a little longer, because it's a new concept for the package.

**Comment by huykon** [comment]
@byrichardpowell yes I think to grap admin API, our package is supporting now, I want to get storefront API at my app proxy remix loader route so do you have idea to get it?

**Comment by byrichardpowell** [comment]
Hey @huykon,

Right now `@shopify/shopify-app-remix` doesn't support the storefront API, but I think you can get a storefront client using `@shopify/shopify-api-js`, which the Remix package is built upon.  Docs here: https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/clients/Storefront.md

I'm fairly sure we'll be adding the storefront client to the Remix package, but hopefully the docs above can be helpful in the meantime.

**Comment by blanklob** [comment]
Hey, thanks for considering this.

**Online Store Example**

I'm wondering what an example of the theme app extension would look like from a liquid snippet for instance. Additionally, 

**Admin Access**

App proxies are often used to update specific customer data or metadata (metafields/metaobjects). How is this possible with the current approach using the SF API?

Thanks!

**Comment by byrichardpowell** [comment]
Thanks @blanklob 

**Online Store Example**

> I'm wondering what an example of the theme app extension would look like from a liquid snippet for instance.

Do you mean how Remix would respond with liquid? If so, I assume something like:

```
import {authenticate} from "~shopify.server"

export async function loader() {
    authenticate.public.appProxy(request)

    return new Response("Liquid code goes here", {status: 200})
}
```

Is that what you are getting at?

**Admin Access**

> App proxies are often used to update specific customer data or metadata (metafields/metaobjects). How is this possible with the current approach using the SF API?

Good point.  I'm going to chat with a few people internally about this.  Technically you could do this:

```
export const loader = async ({ request }) => {
 await authenticate.public.appProxy(request);

  const { searchParams } = new URL(request.url);
  const shop = searchParams.get("shop");
  const {admin} = await unauthenticated.admin(shop);

  admin.graphql()

  // ...etc
};
```

But it may be better if we return the admin context directly from `authenticate.public.appProxy` if mutating metafields is a common use case.

**Comment by byrichardpowell** [comment]
**Update**
Sorry this is taking a little longer than I'd like.  I needed to chat to some domain experts first. Here is what we've landed on for the first release:

```
import {authenticate} from "~/shopify.server"

export async function loader({request}) {
  const {admin, session, liquid} = authenticate.public.appProxy(request)

  // If there is a session for the shop you can access admin API's
  // admin.graphql()
  // admin.rest.get()
  // admin.rest.resources
  // If there is no session, these properties will be undefined

  // The signature of liquid function matches Remix's json function:
  // https://remix.run/docs/en/main/utils/json
  // Except it takes a 3rd argument `{layout: false}`
  // If passed Shopify will render the liquid Response outside of themes layout. 
  return liquid("Hello {{shop.name}}")
}
```

**Comment by byrichardpowell** [comment]
@itszoose 

> Does that mean that in the meantime we have no way of authenticating the proxy requests?

Unfortunately.  Really sorry about that. We should release a new version of `@shopify/shopify-app-remix` early next week.

> Also if you could shed some light on what the authenticate.public() method does, and whether I can trust it to block requests that aren't coming from the store's front end? Thank you.

`authenticate.public()` is really for authenticating checkout extension requests.  We made a mistake here because that's not clear in the name.  Eventually we'll deprecate `authenticate.public()` in favor of `authenticate.public.checkout()`, but for the time being `authenticate.public()` will continue to work.

**Comment by byrichardpowell** [comment]
@blanklob You can read about how to auth an app proxy request here: https://shopify.dev/docs/apps/online-store/app-proxies

The WIP implementation of this is:

1. In the Remix Package: https://github.com/Shopify/shopify-app-js/blob/42f4b2c5555c83a3e0315939b9c23ac7821aeeaf/packages/shopify-app-remix/src/server/authenticate/public/appProxy/authenticate.ts#L22-L40
2. Which calls this: https://github.com/Shopify/shopify-api-js/blob/main/lib/utils/hmac-validator.ts#L47

As far as I can see, I don't think there are any special headers involved in authentication.  It's all URL Params which are added by Shopify.

**Comment by byrichardpowell** [comment]
@itszoose  It's strictly for checkout requests.  Imagine it's called `authenticate.public.checkout` not `authenticate.public`

**Comment by byrichardpowell** [comment]
Hey everyone 👋 

We've released version `1.2.1` of `@shopify/shopify-app-remix` ([Changelog](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-remix/CHANGELOG.md)).  This version contains a new API for authenticating app proxy requests.

### Returning Liquid Responses

```ts
// app/routes/**\/.ts
import {authenticate} from '~/shopify.server';

export async function loader({request}) {
  const {liquid} = authenticate.public.appProxy(request);

  return liquid('Hello {{shop.name}}');
}
```

### Using the admin GraphQL API

```ts
// app/routes/**\/.ts
import {authenticate} from '~/shopify.server';

export async function loader({request}) {
  const {liquid, admin} = authenticate.public.appProxy(request);

  const response = await admin.graphql('QUERY');
  const json = await response.json();

  return json(json);
}
```

### WIP: Storefront API
This release does not contain the storefront API, but that is next on my list.  I'm still figuring this out, but it may look something like this:


```ts
// app/routes/**\/.ts
import {authenticate} from '~/shopify.server';

export async function loader({request}) {
  const {storefront} = authenticate.public.appProxy(request);

  const response = await storefront.graphql("QUERY GOES HERE")
  const json = await response.json();

  return json(json);
}
```

You won't be able to use this storefront API until a later release

**Comment by blanklob** [comment]
Awesome thanks!

**Comment by LHongy** [comment]
Hello @byrichardpowell, 
Could you show me an example of checkout extension requests? Or guide me to a documentation?
I was looking at this doc, still not sure how it should work.

**Comment by byrichardpowell** [comment]
Hey @LHongy 

That looks correct to me, incase it helps here is a tutorial that includes authenticating a checkout request: https://shopify.dev/docs/apps/checkout/product-offers/post-purchase/getting-started#define-the-offer-and-sign-changeset-endpoints

**Comment by LHongy** [comment]
@byrichardpowell 
Does this one also work?
Use authenticate.public on a request from checkout-ui-extension

![image](https://github.com/Shopify/shopify-app-template-remix/assets/21149156/2a566815-b7c7-48cc-95a7-8c3c51a10252)
https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/apis/standardapi

**Comment by LHongy** [comment]
Thanks a lot!

**Comment by joelvh** [comment]
@byrichardpowell is there an example of how a Remix app should be configured to make sure all pages and assets go through the app proxy? (This is to render HTML, not JSON or Liquid.)

Thanks!

**Comment by pkyek1** [comment]
@byrichardpowell @huykon @huykon 

any update ??

**Comment by byrichardpowell** [comment]
Hey everyone 👋 

We've released [version 1.3.0](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-remix/CHANGELOG.md#130) of `@shopify/shopify-app-remix`.  This contains 2 ways to access the storefront API:

App Proxy

  ```ts
  import {json} from '@remix-run/node';
  import {authenticate} from '~/shopify.server';

  export async function loader({request}) {
    const {storefront} = await authenticate.public.appProxy(request);
    const response = await storefront.graphql('{blogs(first: 10) {nodes{id}}}');

    return json(await response.json());
  }
  ```

Unauthenticated Storefront

  ```ts
  import {json} from '@remix-run/node';
  import {unauthenticated} from '~/shopify.server';
  import {customAuthenticateRequest} from '~/helpers';

  export async function loader({request}) {
    await customAuthenticateRequest(request);

    const {storefront} = await unauthenticated.storefront(
      'my-shop.myshopify.com',
    );
    const response = await storefront.graphql('{blogs(first: 10) {nodes{id}}}');

    return json(await response.json());
  }
  ```

There is a lot of discussion in this PR, but the original post is about App Proxy.  To solve this we've released:

1. A new `authenticate.public.appProxy(request)`
2. A storefront API client (see above).

Given this solves the discussions around App Proxy I'm going to close this issue.

--------

@pkyek1 since this is a question about the GraphQL API please could you open a separate issue or ask in our partner Slack: https://join.slack.com/t/shopifypartners/shared_invite/zt-sdr2quab-mGkzkttZ2hnVm0~8noSyvw

@mikesosa in my experiments CORS wasn't an issue since App Proxy is a server to server request.  You should be able to configure your app proxy, and then use `authenticate.public.appProxy()` without worrying about CORS.

**Comment by joelvh** [comment]
@blanklob or anyone else run into signature validation errors with actions? I've opened https://github.com/Shopify/shopify-app-js/issues/455 with details of what I've run into. Thanks for sharing your thoughts.

**Comment by thangcqUET** [comment]
> We've released [version 1.3.0](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-remix/CHANGELOG.md#130) of `@shopify/shopify-app-remix`. This contains 2 ways to access the storefront API:
> 
> App Proxy
> 
> ```ts
> import {json} from '@remix-run/node';
> import {authenticate} from '~/shopify.server';
> 
> export async function loader({request}) {
>   const {storefront} = await authenticate.public.appProxy(request);
>   const response = await storefront.graphql('{blogs(first: 10) {nodes{id}}}');
> 
>   return json(await response.json());
> }
> ```

@byrichardpowell  Thank for the update. But I have the issue when use it. 

I use the `"@shopify/shopify-app-remix": "^1.3.0"` version
When I receive request which is called from Shopify theme app through App proxy, I use this way to get admin:
```
import { authenticate } from "../shopify.server";
export const action = async ({ request }) => {
  try {
    // https://github.com/Shopify/shopify-app-template-remix/issues/295
    // https://shopify.dev/docs/api/shopify-app-remix/v1/authenticate/public/app-proxy
    const result = await authenticate.public.appProxy(request);
    console.log("result");
    console.log(result);
```

But it just returned undefined. Do you know what happen here:
```
18:12:19 │ remix      │ [shopify-app/INFO] Authenticating app proxy request
18:12:19 │ remix      │ result
18:12:19 │ remix      │ {
18:12:19 │ remix      │   liquid: [Function: liquid],
18:12:19 │ remix      │   session: undefined,
18:12:19 │ remix      │   admin: undefined,
18:12:19 │ remix      │   storefront: undefined
18:12:19 │ remix      │ }
```
Thanks in advance.

**Comment by liam997** [comment]
Hi @barryrichardson ,

Sorry to bother you but I follow the [post purchase guide](https://shopify.dev/docs/apps/checkout/product-offers/post-purchase/getting-started#define-the-offer-and-sign-changeset-endpoints) but it still return 401 CORS error.

**Comment by liam997** [comment]
Hi @byrichardpowell,

I follow the guide but still face the error 401 CORS. I've opened [shopify-app-js/issues/492](https://github.com/Shopify/shopify-app-js/issues/492). Thanks in advance

**Comment by joeainsworth** [comment]
Can anybody help?

I'm trying to return a liquid response from a remix route via the app template.

```
import { authenticate } from "../shopify.server";

export async function loader({ request }) {
  const { liquid } = authenticate.public.appProxy(request);

  return liquid("Hello {{shop.name}}");
}
```

But I'm getting the following error:

`10:06:35 │ remix      │ TypeError: liquid is not a 
function`

How do I include the liquid function?

**Comment by nboliver-ventureweb** [comment]
@joeainsworth Looks like you may be missing an `await`. I think there may have been an error in the docs previously. 

```javascript
  const { admin, session, liquid } = await authenticate.public.appProxy(
    request,
  );
```

Unfortunately I found that client side JS doesn't work on app proxy pages, have an issue open here: https://github.com/Shopify/shopify-app-template-remix/issues/436 - hopefully it gets addressed at some point and there's a way to build in client-side JS.
