### ISSUE TITLE
Redirects thrown from authenticated routes cause application error

### ISSUE THREAD

**Issue by btomaj** [Shopify/shopify-app-template-remix#317]
# Issue summary

This issue was filed in the shopify-app-js repo, but I think it might belong here: https://github.com/Shopify/shopify-app-js/issues/374

**Comment by btomaj** [comment]
I was able to reproduce this with a barebones implementation:

Route A
```javascript
import { redirect } from "@remix-run/node";                                      
import { authenticate } from "../shopify.server";                                

export async function loader({ request }) {                                      
    await authenticate.admin(request);                                           
    throw redirect("/app/error");                                                
}    
``` 
Route B
```javascript
export default function () {}
```

**Comment by btomaj** [comment]
This issue only occurs if Route A is the first page loaded, is refreshed, or is accessed directly.

**Comment by btomaj** [comment]
It looks like the redirect causes a race condition that causes an infinite loop because Remix tries to reload the page.

```
[Debug] [bugsnag] – "Loaded!" (vendors-node_modules_bugsnag_js_browser_notifier_js-node_modules_bugsnag_plugin-react_dist_bu-4c8368-ca7ba3259abea3d0334c688f1ae481f899f0cb6d844bd1049a20086c67650d81.js, line 2)
[Error] Unable to post message to https://forms.shopifyapps.com. Recipient has origin https://baseline-afternoon-nature-crop.trycloudflare.com.

	postMessage
	(anonymous function) (vendors-node_modules_shopify_app-bridge-host_index_js-a2a54210984567e5.js:1:1762)
[Error] Initial URL (/app/error) does not match URL at time of hydration (/app/test), reloading page...
	RemixBrowser (chunk-K3SBKXTE.js:7705)
	renderWithHooks (chunk-GIAAE3CH.js:12171)
	mountIndeterminateComponent (chunk-GIAAE3CH.js:14921)
	beginWork$1 (chunk-GIAAE3CH.js:19749)
	performUnitOfWork (chunk-GIAAE3CH.js:19194)
	workLoopConcurrent (chunk-GIAAE3CH.js:19185)
	renderRootConcurrent (chunk-GIAAE3CH.js:19160)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18674)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] TypeError: undefined is not an object (evaluating 'module.links')
	(anonymous function) (chunk-K3SBKXTE.js:5796)
	map
	getLinksForMatches (chunk-K3SBKXTE.js:5793)
	mountMemo (chunk-GIAAE3CH.js:12817)
	useMemo (chunk-GIAAE3CH.js:13141)
	Links (chunk-K3SBKXTE.js:6218)
	renderWithHooks (chunk-GIAAE3CH.js:12171)
	mountIndeterminateComponent (chunk-GIAAE3CH.js:14921)
	callCallback2 (chunk-GIAAE3CH.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-GIAAE3CH.js:3699)
	invokeGuardedCallback (chunk-GIAAE3CH.js:3733)
	beginWork$1 (chunk-GIAAE3CH.js:19761)
	performUnitOfWork (chunk-GIAAE3CH.js:19194)
	workLoopConcurrent (chunk-GIAAE3CH.js:19185)
	renderRootConcurrent (chunk-GIAAE3CH.js:19160)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18674)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
	printWarning (chunk-GIAAE3CH.js:521)
	error (chunk-GIAAE3CH.js:505)
	errorHydratingContainer (chunk-GIAAE3CH.js:8769)
	recoverFromConcurrentError (chunk-GIAAE3CH.js:18729)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18680)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] TypeError: undefined is not an object (evaluating 'module.links')
	(anonymous function) (chunk-K3SBKXTE.js:5796)
	map
	getLinksForMatches (chunk-K3SBKXTE.js:5793)
	mountMemo (chunk-GIAAE3CH.js:12817)
	useMemo (chunk-GIAAE3CH.js:13141)
	Links (chunk-K3SBKXTE.js:6218)
	renderWithHooks (chunk-GIAAE3CH.js:12171)
	mountIndeterminateComponent (chunk-GIAAE3CH.js:14921)
	callCallback2 (chunk-GIAAE3CH.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-GIAAE3CH.js:3699)
	invokeGuardedCallback (chunk-GIAAE3CH.js:3733)
	beginWork$1 (chunk-GIAAE3CH.js:19761)
	performUnitOfWork (chunk-GIAAE3CH.js:19194)
	workLoopSync (chunk-GIAAE3CH.js:19133)
	renderRootSync (chunk-GIAAE3CH.js:19112)
	recoverFromConcurrentError (chunk-GIAAE3CH.js:18732)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18680)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] TypeError: Right side of assignment cannot be destructured
	RemixRoute (chunk-K3SBKXTE.js:6048)
	renderWithHooks (chunk-GIAAE3CH.js:12171)
	mountIndeterminateComponent (chunk-GIAAE3CH.js:14921)
	callCallback2 (chunk-GIAAE3CH.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-GIAAE3CH.js:3699)
	invokeGuardedCallback (chunk-GIAAE3CH.js:3733)
	beginWork$1 (chunk-GIAAE3CH.js:19761)
	performUnitOfWork (chunk-GIAAE3CH.js:19194)
	workLoopSync (chunk-GIAAE3CH.js:19133)
	renderRootSync (chunk-GIAAE3CH.js:19112)
	recoverFromConcurrentError (chunk-GIAAE3CH.js:18732)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18680)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] TypeError: Right side of assignment cannot be destructured
	errorBoundary (app-EB2ZDQOO.js:15888)
	renderWithHooks (chunk-GIAAE3CH.js:12171)
	mountIndeterminateComponent (chunk-GIAAE3CH.js:14921)
	callCallback2 (chunk-GIAAE3CH.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-GIAAE3CH.js:3699)
	invokeGuardedCallback (chunk-GIAAE3CH.js:3733)
	beginWork$1 (chunk-GIAAE3CH.js:19761)
	performUnitOfWork (chunk-GIAAE3CH.js:19194)
	workLoopSync (chunk-GIAAE3CH.js:19133)
	renderRootSync (chunk-GIAAE3CH.js:19112)
	recoverFromConcurrentError (chunk-GIAAE3CH.js:18732)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18680)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] TypeError: undefined is not an object (evaluating 'routeModules[match.id].handle')
	(anonymous function) (chunk-K3SBKXTE.js:6731)
	map
	mountMemo (chunk-GIAAE3CH.js:12817)
	useMemo (chunk-GIAAE3CH.js:13141)
	ScrollRestoration2 (chunk-K3SBKXTE.js:7756)
	renderWithHooks (chunk-GIAAE3CH.js:12171)
	mountIndeterminateComponent (chunk-GIAAE3CH.js:14921)
	callCallback2 (chunk-GIAAE3CH.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-GIAAE3CH.js:3699)
	invokeGuardedCallback (chunk-GIAAE3CH.js:3733)
	beginWork$1 (chunk-GIAAE3CH.js:19761)
	performUnitOfWork (chunk-GIAAE3CH.js:19194)
	workLoopSync (chunk-GIAAE3CH.js:19133)
	renderRootSync (chunk-GIAAE3CH.js:19112)
	recoverFromConcurrentError (chunk-GIAAE3CH.js:18732)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18680)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] The above error occurred in the <Links> component:

Links@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:6212:22
head
html
App
RemixRoute@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:6037:5
RenderedRoute@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3658:11
RenderErrorBoundary@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:4239:14
DataRoutes@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3955:12
Router@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:4038:12
RouterProvider@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3905:11
RemixErrorBoundary@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:5625:10
RemixBrowser@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:7712:48

React will try to recreate this component tree from scratch using the error boundary you provided, RenderErrorBoundary.
	logCapturedError (chunk-GIAAE3CH.js:14036)
	callback (chunk-GIAAE3CH.js:14082)
	callCallback (chunk-GIAAE3CH.js:10511)
	commitUpdateQueue (chunk-GIAAE3CH.js:10528)
	commitLayoutEffectOnFiber (chunk-GIAAE3CH.js:17065)
	commitLayoutMountEffects_complete (chunk-GIAAE3CH.js:17976)
	commitLayoutEffects_begin (chunk-GIAAE3CH.js:17965)
	commitLayoutEffects (chunk-GIAAE3CH.js:17916)
	commitRootImpl (chunk-GIAAE3CH.js:19349)
	commitRoot (chunk-GIAAE3CH.js:19273)
	finishConcurrentRender (chunk-GIAAE3CH.js:18756)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18714)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] React Router caught the following error during render (2)
TypeError: undefined is not an object (evaluating 'module.links') — links.js:29
{componentStack: "↵Links@https://baseline-afternoon-nature-crop.tryc…flare.com/build/_shared/chunk-K3SBKXTE.js:7712:48"}
	componentDidCatch (chunk-K3SBKXTE.js:4266)
	callback (chunk-GIAAE3CH.js:14088)
	callCallback (chunk-GIAAE3CH.js:10511)
	commitUpdateQueue (chunk-GIAAE3CH.js:10528)
	commitLayoutEffectOnFiber (chunk-GIAAE3CH.js:17065)
	commitLayoutMountEffects_complete (chunk-GIAAE3CH.js:17976)
	commitLayoutEffects_begin (chunk-GIAAE3CH.js:17965)
	commitLayoutEffects (chunk-GIAAE3CH.js:17916)
	commitRootImpl (chunk-GIAAE3CH.js:19349)
	commitRoot (chunk-GIAAE3CH.js:19273)
	finishConcurrentRender (chunk-GIAAE3CH.js:18756)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18714)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] The above error occurred in the <ErrorBoundary> component:

ErrorBoundary@https://baseline-afternoon-nature-crop.trycloudflare.com/build/routes/app-EB2ZDQOO.js:16153:63
RemixRouteError@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:6057:5
RenderErrorBoundary@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:4239:14
Outlet@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:4025:25
body
html
App
RemixRoute@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:6037:5
RenderedRoute@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3658:11
RenderErrorBoundary@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:4239:14
DataRoutes@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3955:12
Router@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:4038:12
RouterProvider@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3905:11
RemixErrorBoundary@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:5625:10
RemixBrowser@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:7712:48

React will try to recreate this component tree from scratch using the error boundary you provided, RenderErrorBoundary.
	logCapturedError (chunk-GIAAE3CH.js:14036)
	callback (chunk-GIAAE3CH.js:14082)
	callCallback (chunk-GIAAE3CH.js:10511)
	commitUpdateQueue (chunk-GIAAE3CH.js:10528)
	commitLayoutEffectOnFiber (chunk-GIAAE3CH.js:17065)
	commitLayoutMountEffects_complete (chunk-GIAAE3CH.js:17976)
	commitLayoutEffects_begin (chunk-GIAAE3CH.js:17965)
	commitLayoutEffects (chunk-GIAAE3CH.js:17916)
	commitRootImpl (chunk-GIAAE3CH.js:19349)
	commitRoot (chunk-GIAAE3CH.js:19273)
	finishConcurrentRender (chunk-GIAAE3CH.js:18756)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18714)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] React Router caught the following error during render (2)
TypeError: Right side of assignment cannot be destructured — components.js:58
{componentStack: "↵ErrorBoundary@https://baseline-afternoon-nature-c…flare.com/build/_shared/chunk-K3SBKXTE.js:7712:48"}
	componentDidCatch (chunk-K3SBKXTE.js:4266)
	callback (chunk-GIAAE3CH.js:14088)
	callCallback (chunk-GIAAE3CH.js:10511)
	commitUpdateQueue (chunk-GIAAE3CH.js:10528)
	commitLayoutEffectOnFiber (chunk-GIAAE3CH.js:17065)
	commitLayoutMountEffects_complete (chunk-GIAAE3CH.js:17976)
	commitLayoutEffects_begin (chunk-GIAAE3CH.js:17965)
	commitLayoutEffects (chunk-GIAAE3CH.js:17916)
	commitRootImpl (chunk-GIAAE3CH.js:19349)
	commitRoot (chunk-GIAAE3CH.js:19273)
	finishConcurrentRender (chunk-GIAAE3CH.js:18756)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18714)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] The above error occurred in the <ScrollRestoration2> component:

ScrollRestoration2@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:7752:9
body
html
App
RemixRoute@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:6037:5
RenderedRoute@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3658:11
RenderErrorBoundary@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:4239:14
DataRoutes@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3955:12
Router@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:4038:12
RouterProvider@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:3905:11
RemixErrorBoundary@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:5625:10
RemixBrowser@https://baseline-afternoon-nature-crop.trycloudflare.com/build/_shared/chunk-K3SBKXTE.js:7712:48

React will try to recreate this component tree from scratch using the error boundary you provided, RenderErrorBoundary.
	logCapturedError (chunk-GIAAE3CH.js:14036)
	callback (chunk-GIAAE3CH.js:14082)
	callCallback (chunk-GIAAE3CH.js:10511)
	commitUpdateQueue (chunk-GIAAE3CH.js:10528)
	commitLayoutEffectOnFiber (chunk-GIAAE3CH.js:17065)
	commitLayoutMountEffects_complete (chunk-GIAAE3CH.js:17976)
	commitLayoutEffects_begin (chunk-GIAAE3CH.js:17965)
	commitLayoutEffects (chunk-GIAAE3CH.js:17916)
	commitRootImpl (chunk-GIAAE3CH.js:19349)
	commitRoot (chunk-GIAAE3CH.js:19273)
	finishConcurrentRender (chunk-GIAAE3CH.js:18756)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18714)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] React Router caught the following error during render (2)
TypeError: undefined is not an object (evaluating 'routeModules[match.id].handle') — components.js:860
{componentStack: "↵ScrollRestoration2@https://baseline-afternoon-nat…flare.com/build/_shared/chunk-K3SBKXTE.js:7712:48"}
	componentDidCatch (chunk-K3SBKXTE.js:4266)
	callback (chunk-GIAAE3CH.js:14088)
	callCallback (chunk-GIAAE3CH.js:10511)
	commitUpdateQueue (chunk-GIAAE3CH.js:10528)
	commitLayoutEffectOnFiber (chunk-GIAAE3CH.js:17065)
	commitLayoutMountEffects_complete (chunk-GIAAE3CH.js:17976)
	commitLayoutEffects_begin (chunk-GIAAE3CH.js:17965)
	commitLayoutEffects (chunk-GIAAE3CH.js:17916)
	commitRootImpl (chunk-GIAAE3CH.js:19349)
	commitRoot (chunk-GIAAE3CH.js:19273)
	finishConcurrentRender (chunk-GIAAE3CH.js:18756)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18714)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
	reportError (chunk-GIAAE3CH.js:14755)
	commitRootImpl (chunk-GIAAE3CH.js:19399)
	commitRoot (chunk-GIAAE3CH.js:19273)
	finishConcurrentRender (chunk-GIAAE3CH.js:18756)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18714)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] TypeError: undefined is not an object (evaluating 'routeModules[match.id].handle') — components.js:860
	(anonymous function) (chunk-K3SBKXTE.js:5662)
	commitHookEffectListMount (chunk-GIAAE3CH.js:16904)
	commitPassiveMountOnFiber (chunk-GIAAE3CH.js:18152)
	commitPassiveMountEffects_complete (chunk-GIAAE3CH.js:18125)
	commitPassiveMountEffects_begin (chunk-GIAAE3CH.js:18115)
	commitPassiveMountEffects (chunk-GIAAE3CH.js:18105)
	flushPassiveEffectsImpl (chunk-GIAAE3CH.js:19486)
	flushPassiveEffects (chunk-GIAAE3CH.js:19443)
	(anonymous function) (chunk-GIAAE3CH.js:19324)
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] TypeError: undefined is not an object (evaluating 'routeModules[match.id].handle') — components.js:860
	(anonymous function) (chunk-K3SBKXTE.js:5662)
	commitHookEffectListMount (chunk-GIAAE3CH.js:16904)
	invokePassiveEffectMountInDEV (chunk-GIAAE3CH.js:18320)
	invokeEffectsInDev (chunk-GIAAE3CH.js:19697)
	commitDoubleInvokeEffectsInDEV (chunk-GIAAE3CH.js:19682)
	flushPassiveEffectsImpl (chunk-GIAAE3CH.js:19499)
	flushPassiveEffects (chunk-GIAAE3CH.js:19443)
	(anonymous function) (chunk-GIAAE3CH.js:19324)
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
[Error] TypeError: null is not an object (evaluating 'window.history.state.key') — test:10
	(anonymous function) (test:15)
	Global Code (test:18)
	write
	(anonymous function) (app-bridge.js:1:21755)
[Error] Initial URL (/app/error) does not match URL at time of hydration (/app/test), reloading page...
	RemixBrowser (chunk-K3SBKXTE.js:7705)
	renderWithHooks (chunk-GIAAE3CH.js:12171)
	mountIndeterminateComponent (chunk-GIAAE3CH.js:14921)
	beginWork$1 (chunk-GIAAE3CH.js:19749)
	performUnitOfWork (chunk-GIAAE3CH.js:19194)
	workLoopConcurrent (chunk-GIAAE3CH.js:19185)
	renderRootConcurrent (chunk-GIAAE3CH.js:19160)
	performConcurrentWorkOnRoot (chunk-GIAAE3CH.js:18674)
	performConcurrentWorkOnRoot
	workLoop (chunk-GIAAE3CH.js:197)
	flushWork (chunk-GIAAE3CH.js:176)
	performWorkUntilDeadline (chunk-GIAAE3CH.js:384)
```

The repeat from here.

**Comment by byrichardpowell** [comment]
Hey @btomaj 

In your example you have:

```
export default function () {}
```

I would expect this to cause issues because the return value of the component is `undefined`.  What happens if you remove the default export, or if the default export returns some React code?

**Comment by byrichardpowell** [comment]
Hey @btomaj 

`{ relative: "path" }` isn't supported by the helper we provide.  Looking at the [Remix doc's]( https://remix.run/docs/en/main/utils/redirect) I don't see it supported either by Remix either?

>@byrichardpowell a-ha! That makes sense! How do I use relative URLs with this redirect? It doesn't seem to be following the remix path conventions. redirect("..") takes me to the _index.jsx route (not to be mistaken for app/_index.jsx) instead of the parent route.

I'm not sure I understand the issue here.  Please could you reply with the code you are trying to run?

**Comment by byrichardpowell** [comment]
I can't find any docs on relative paths, so I think you might ned to use absolute paths.

Since the original issue has been addressed I'm going to close this.

Good luck with your app!

**Comment by mufftee** [comment]
@byrichardpowell for me the issue still persists:
```
export async function loader({ request }) {
  const { admin, redirect } = await authenticate.admin(request);
  const completeSetup = await isAppSetupComplete({ admin: admin });

  if (completeSetup) {
    return redirect(`/bundles`);
  } else if (!completeSetup) {
    return redirect(`/setup`);
  }


  return json({ showForm: Boolean(login) });
}
```
results in:
```
18:09:10 │ remix      │ ErrorResponseImpl {
18:09:10 │ remix      │   status: 200,
18:09:10 │ remix      │   statusText: '',
18:09:10 │ remix      │   internal: false,
18:09:10 │ remix      │   data: '\n' +
18:09:10 │ remix      │     '      <script data-api-key="xxx" src="https://cdn.shopify.com/shopifycloud/app-bridge.js"></script>\n' +
18:09:10 │ remix      │     '      <script>window.open("https://phones-container-cancer-forestry.trycloudflare.com/setup?embedded=1&...", "_self")</script>\n' +
18:09:10 │ remix      │     '    '
18:09:10 │ remix      │ }
```

in my `routes/_index/routes.jsx` if i navigate to `/setup` directly everything works fine, also after a refresh everything works correkt

**Comment by mufftee** [comment]
Solved it:

```
export async function loader({ request }) {
  const url = new URL(request.url);
  const shop = url.searchParams.get("shop");
  const { admin } = await unauthenticated.admin(shop);
  const completeSetup = await isAppSetupComplete({ admin: admin, smallCheck: true });

  if (shop && !completeSetup) {
    throw redirect(`/app/setup?${url.searchParams.toString()}`);
  } else if (shop && completeSetup) {
    throw redirect(`/app/bundles?${url.searchParams.toString()}`);
  }

  return json({ showForm: Boolean(login) });
}
```

this is how you can do a redirect on the index page
