### ISSUE TITLE
This app can’t load due to an issue with browser cookies. 

### ISSUE THREAD

**Issue by benjisoft** [Shopify/shopify-app-template-remix#332]
# Issue summary

When generating an app via the `npm init @shopify/app@latest` when running `npm run dev` and installing the app on the Shopify store. The following error is presented ```This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, [switching to another browser](https://community.shopify.com/c/Shopify-Apps/Some-Third-Party-Apps-may-not-be-accessible-on-Chrome-80-update/m-p/650220/thread-id/20503), or contacting the developer to get support.```

- `@shopify/shopify-app-remix` version: 1.1.0
- Node version: 18.6.1
- Operating system: Windows 11

```
11:01:05 │ remix    │
11:01:05 │ remix    │  💿  remix dev
11:01:05 │ remix    │
11:01:05 │ webhooks │ Sending APP_UNINSTALLED webhook to app server
11:01:06 │ remix    │  info  building...
11:01:08 │ webhooks │ App isn't responding yet, retrying in 5 seconds
11:01:08 │ remix    │  info  built (2.2s)
11:01:09 │ remix    │ [shopify-api/INFO] version 7.6.0, environment Remix
11:01:09 │ remix    │ Remix App Server started at http://localhost:52710 (http://10.100.0.140:52710)
11:01:10 │ remix    │
11:01:13 │ webhooks │ APP_UNINSTALLED webhook delivered
11:01:13 │ remix    │ POST /webhooks 200 - - 11.443 ms                                                         
11:01:14 │ remix    │ GET /?embedded=1&hmac=efc4f86395d4536100fad1286697fc03cb0d7f4c2f946ac31d4e9b5a8ad5e635&ho
st=YmVuLWRldi12aXNpLm15c2hvcGlmeS5jb20vYWRtaW4&locale=en&session=a129c2b323dbc9db9d6bede4b60b6012cf41ec257c06fd
efe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994599 302 - - 2.700 ms
11:01:14 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:14 │ remix    │ [shopify-app/INFO] Authenticating admin request                                          
11:01:14 │ remix    │ [shopify-app/INFO] Shop hasn't installed app yet, redirecting to OAuth | {shop:          
ben-dev-visi.myshopify.com}                                                                                    
11:01:14 │ remix    │ [shopify-app/INFO] Shop hasn't installed app yet, redirecting to OAuth | {shop:          
ben-dev-visi.myshopify.com}                                                                                    
11:01:14 │ remix    │ GET /app?embedded=1&hmac=efc4f86395d4536100fad1286697fc03cb0d7f4c2f946ac31d4e9b5a8ad5e635
&host=YmVuLWRldi12aXNpLm15c2hvcGlmeS5jb20vYWRtaW4&locale=en&session=a129c2b323dbc9db9d6bede4b60b6012cf41ec257c0
6fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994599 302 - - 7.283 ms                    
11:01:14 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:14 │ remix    │ GET /auth/exit-iframe?embedded=1&hmac=efc4f86395d4536100fad1286697fc03cb0d7f4c2f946ac31d4
e9b5a8ad5e635&host=YmVuLWRldi12aXNpLm15c2hvcGlmeS5jb20vYWRtaW4&locale=en&session=a129c2b323dbc9db9d6bede4b60b60
12cf41ec257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994599&exitIframe=%2Fauth%3Fsh
op%3Dben-dev-visi.myshopify.com 200 - - 2.151 ms                                                               
11:01:14 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:14 │ remix    │ [shopify-app/INFO] Handling OAuth begin request                                          
11:01:14 │ remix    │ [shopify-api/INFO] Beginning OAuth | {shop: ben-dev-visi.myshopify.com, isOnline: false, 
callbackPath: /auth/callback}                                                                                  
11:01:14 │ remix    │ GET /auth?shop=ben-dev-visi.myshopify.com 302 - - 3.499 ms                               
11:01:15 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:15 │ remix    │ [shopify-api/ERROR] Could not find OAuth cookie | {shop: ben-dev-visi.myshopify.com}     
11:01:15 │ remix    │ [shopify-app/ERROR] Error during OAuth callback | {error: Cannot complete OAuth process. 
Could not find an OAuth cookie for shop url: ben-dev-visi.myshopify.com}                                       
11:01:15 │ remix    │ [shopify-app/INFO] Handling OAuth callback request                                       
11:01:15 │ remix    │ [shopify-api/INFO] Completing OAuth | {shop: ben-dev-visi.myshopify.com}                 
11:01:15 │ remix    │ [shopify-app/INFO] Handling OAuth begin request                                          
11:01:15 │ remix    │ [shopify-api/INFO] Beginning OAuth | {shop: ben-dev-visi.myshopify.com, isOnline: false, 
callbackPath: /auth/callback}                                                                                  
11:01:15 │ remix    │ GET /auth/callback?code=fefbdd4c36b974842ffb1eabfb74e13f&hmac=9e5b6cfb1f555fe3a3d79e34c06
8a8b1d41e9e3ffc97c5711b58d305d97eaf85&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&shop=ben-dev-visi.m
yshopify.com&state=646004825749345&timestamp=1693994601 302 - - 4.207 ms                                       
11:01:16 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:16 │ remix    │ [shopify-app/INFO] Handling OAuth callback request
11:01:16 │ remix    │ [shopify-api/ERROR] Could not find OAuth cookie | {shop: ben-dev-visi.myshopify.com}     
11:01:16 │ remix    │ [shopify-app/ERROR] Error during OAuth callback | {error: Cannot complete OAuth process. 
Could not find an OAuth cookie for shop url: ben-dev-visi.myshopify.com}                                       
11:01:16 │ remix    │ [shopify-api/INFO] Completing OAuth | {shop: ben-dev-visi.myshopify.com}                 
11:01:16 │ remix    │ [shopify-app/INFO] Handling OAuth begin request                                          
11:01:16 │ remix    │ [shopify-api/INFO] Beginning OAuth | {shop: ben-dev-visi.myshopify.com, isOnline: false, 
callbackPath: /auth/callback}                                                                                  
11:01:16 │ remix    │ GET /auth/callback?code=79b1289b3de2f0b9c750f5dea90b1159&hmac=5dcd9156cb4228b0c8ed6056cc5
ccfc7373b7db4e91709b13f1866367f5553f7&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&shop=ben-dev-visi.m
yshopify.com&state=704469826675140&timestamp=1693994601 302 - - 2.576 ms                                       
11:01:16 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:16 │ remix    │ [shopify-api/ERROR] Could not find OAuth cookie | {shop: ben-dev-visi.myshopify.com}     
11:01:16 │ remix    │ [shopify-app/ERROR] Error during OAuth callback | {error: Cannot complete OAuth process. 
Could not find an OAuth cookie for shop url: ben-dev-visi.myshopify.com}                                       
11:01:16 │ remix    │ [shopify-app/INFO] Handling OAuth callback request                                       
11:01:16 │ remix    │ [shopify-api/INFO] Completing OAuth | {shop: ben-dev-visi.myshopify.com}                 
11:01:16 │ remix    │ [shopify-app/INFO] Handling OAuth begin request                                          
11:01:16 │ remix    │ [shopify-api/INFO] Beginning OAuth | {shop: ben-dev-visi.myshopify.com, isOnline: false, 
callbackPath: /auth/callback}                                                                                  
11:01:16 │ remix    │ GET /auth/callback?code=16a46a374adc781bf9989386eac12240&hmac=342187e7ecb1e4edf07389cd2f3
9aa46a2ddbe17f88f79aee9e9203e09b056f5&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&shop=ben-dev-visi.m
yshopify.com&state=856371861022754&timestamp=1693994602 302 - - 4.328 ms                                       
11:01:18 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:18 │ remix    │ GET /auth/exit-iframe?embedded=1&hmac=efc4f86395d4536100fad1286697fc03cb0d7f4c2f946ac31d4
e9b5a8ad5e635&host=YmVuLWRldi12aXNpLm15c2hvcGlmeS5jb20vYWRtaW4&locale=en&session=a129c2b323dbc9db9d6bede4b60b60
12cf41ec257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994599&exitIframe=%2Fauth%3Fsh
op%3Dben-dev-visi.myshopify.com 200 - - 2.343 ms                                                               
11:01:18 │ remix    │ [shopify-app/INFO] Authenticating admin request                                          
11:01:18 │ remix    │ GET /auth/exit-iframe?embedded=1&hmac=efc4f86395d4536100fad1286697fc03cb0d7f4c2f946ac31d4
e9b5a8ad5e635&host=YmVuLWRldi12aXNpLm15c2hvcGlmeS5jb20vYWRtaW4&locale=en&session=a129c2b323dbc9db9d6bede4b60b60
12cf41ec257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994599&exitIframe=%2Fauth%3Fsh
op%3Dben-dev-visi.myshopify.com 200 - - 1.112 ms                                                               
11:01:18 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:18 │ remix    │ GET /auth/exit-iframe?embedded=1&hmac=efc4f86395d4536100fad1286697fc03cb0d7f4c2f946ac31d4
e9b5a8ad5e635&host=YmVuLWRldi12aXNpLm15c2hvcGlmeS5jb20vYWRtaW4&locale=en&session=a129c2b323dbc9db9d6bede4b60b60
12cf41ec257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994599&exitIframe=%2Fauth%3Fsh
op%3Dben-dev-visi.myshopify.com 200 - - 2.526 ms                                                               
11:01:21 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:01:21 │ remix    │ GET                                                                                      
/auth/exit-iframe?embedded=1&hmac=efc4f86395d4536100fad1286697fc03cb0d7f4c2f946ac31d4e9b5a8ad5e635&host=YmVuLWR
ldi12aXNpLm15c2hvcGlmeS5jb20vYWRtaW4&locale=en&session=a129c2b323dbc9db9d6bede4b60b6012cf41ec257c06fdefe3f0525d
e715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994599&exitIframe=%2Fauth%3Fshop%3Dben-dev-visi.myshopif
y.com/shopify-assets.shopifycdn.com/shopify-marketing_assets/static/shopify-favicon.png 200 - - 3.627 ms       
11:07:27 │ remix    │ GET /?embedded=1&hmac=2a9d0e85bb9b7f70fee3bca536213e6345f9de536580594e9bbb609628cc07d5&ho
st=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&locale=en&session=a129c2b323dbc9db9d6bede4b60b6012cf41ec257
c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994971 302 - - 1.524 ms
11:07:27 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:07:27 │ remix    │ [shopify-app/INFO] Authenticating admin request                                          
11:07:27 │ remix    │ [shopify-app/INFO] Shop hasn't installed app yet, redirecting to OAuth | {shop:          
ben-dev-visi.myshopify.com}                                                                                    
11:07:27 │ remix    │ [shopify-app/INFO] Shop hasn't installed app yet, redirecting to OAuth | {shop:          
ben-dev-visi.myshopify.com}                                                                                    
11:07:27 │ remix    │ GET /app?embedded=1&hmac=2a9d0e85bb9b7f70fee3bca536213e6345f9de536580594e9bbb609628cc07d5
&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&locale=en&session=a129c2b323dbc9db9d6bede4b60b6012cf41ec
257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994971 302 - - 5.551 ms               
11:07:27 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:07:27 │ remix    │ GET /auth/exit-iframe?embedded=1&hmac=2a9d0e85bb9b7f70fee3bca536213e6345f9de536580594e9bb
b609628cc07d5&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&locale=en&session=a129c2b323dbc9db9d6bede4b
60b6012cf41ec257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994971&exitIframe=%2Fauth
%3Fshop%3Dben-dev-visi.myshopify.com 200 - - 1.887 ms                                                          
11:07:27 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:07:27 │ remix    │ [shopify-app/INFO] Handling OAuth begin request
11:07:27 │ remix    │ [shopify-api/INFO] Beginning OAuth | {shop: ben-dev-visi.myshopify.com, isOnline: false, 
callbackPath: /auth/callback}                                                                                  
11:07:27 │ remix    │ GET /auth?shop=ben-dev-visi.myshopify.com 302 - - 3.716 ms                               
11:07:28 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:07:28 │ remix    │ [shopify-app/INFO] Handling OAuth callback request                                       
11:07:28 │ remix    │ [shopify-api/ERROR] Could not find OAuth cookie | {shop: ben-dev-visi.myshopify.com}     
11:07:28 │ remix    │ [shopify-app/ERROR] Error during OAuth callback | {error: Cannot complete OAuth process. 
Could not find an OAuth cookie for shop url: ben-dev-visi.myshopify.com}                                       
11:07:28 │ remix    │ [shopify-api/INFO] Completing OAuth | {shop: ben-dev-visi.myshopify.com}                 
11:07:28 │ remix    │ [shopify-app/INFO] Handling OAuth begin request                                          
11:07:28 │ remix    │ [shopify-api/INFO] Beginning OAuth | {shop: ben-dev-visi.myshopify.com, isOnline: false, 
callbackPath: /auth/callback}                                                                                  
11:07:28 │ remix    │ GET /auth/callback?code=ec23c957dbb24a6cab1a69a15ab92ccb&hmac=3cda1795b53968db7c26a7d2f23
01db27a7f4e88df0fce20917cf121c4f1d293&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&shop=ben-dev-visi.m
yshopify.com&state=229339987898764&timestamp=1693994973 302 - - 10.637 ms                                      
11:07:28 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:07:28 │ remix    │ [shopify-app/INFO] Handling OAuth callback request
11:07:28 │ remix    │ [shopify-api/ERROR] Could not find OAuth cookie | {shop: ben-dev-visi.myshopify.com}     
11:07:28 │ remix    │ [shopify-app/ERROR] Error during OAuth callback | {error: Cannot complete OAuth process. 
Could not find an OAuth cookie for shop url: ben-dev-visi.myshopify.com}                                       
11:07:28 │ remix    │ [shopify-api/INFO] Completing OAuth | {shop: ben-dev-visi.myshopify.com}                 
11:07:28 │ remix    │ [shopify-app/INFO] Handling OAuth begin request                                          
11:07:28 │ remix    │ [shopify-api/INFO] Beginning OAuth | {shop: ben-dev-visi.myshopify.com, isOnline: false, 
callbackPath: /auth/callback}                                                                                  
11:07:28 │ remix    │ GET /auth/callback?code=de98f85f79f27863345904b67854bbc9&hmac=12a0daeb501a30351fcb01aab4f
82009abaf7b5c13f17dea3ec0f37924f426ac&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&shop=ben-dev-visi.m
yshopify.com&state=545284727189158&timestamp=1693994974 302 - - 3.416 ms                                       
11:07:29 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:07:29 │ remix    │ [shopify-api/ERROR] Could not find OAuth cookie | {shop: ben-dev-visi.myshopify.com}     
11:07:29 │ remix    │ [shopify-app/ERROR] Error during OAuth callback | {error: Cannot complete OAuth process. 
Could not find an OAuth cookie for shop url: ben-dev-visi.myshopify.com}                                       
11:07:29 │ remix    │ [shopify-app/INFO] Handling OAuth callback request                                       
11:07:29 │ remix    │ [shopify-api/INFO] Completing OAuth | {shop: ben-dev-visi.myshopify.com}                 
11:07:29 │ remix    │ [shopify-app/INFO] Handling OAuth begin request                                          
11:07:29 │ remix    │ [shopify-api/INFO] Beginning OAuth | {shop: ben-dev-visi.myshopify.com, isOnline: false, 
callbackPath: /auth/callback}                                                                                  
11:07:29 │ remix    │ GET /auth/callback?code=bdb96cd4ebcc9913b5f458ac35e74748&hmac=e984c6bd0c860b190eae3c159c3
1431f94a502442404931b266981a5c43a52a7&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&shop=ben-dev-visi.m
yshopify.com&state=906524719908923&timestamp=1693994974 302 - - 3.903 ms                                       
11:07:35 │ remix    │ GET /?embedded=1&hmac=865e706dcfef78f67251c48fb926f1fca6a180a979e7e73e5e6111202c469150&ho
st=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&locale=en&prefetch=1&session=a129c2b323dbc9db9d6bede4b60b60
12cf41ec257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994978 302 - - 1.283 ms       
11:07:35 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:07:35 │ remix    │ [shopify-app/INFO] Authenticating admin request                                          
11:07:35 │ remix    │ [shopify-app/INFO] Shop hasn't installed app yet, redirecting to OAuth | {shop:          
ben-dev-visi.myshopify.com}                                                                                    
11:07:35 │ remix    │ [shopify-app/INFO] Shop hasn't installed app yet, redirecting to OAuth | {shop:          
ben-dev-visi.myshopify.com}                                                                                    
11:07:35 │ remix    │ GET /app?embedded=1&hmac=865e706dcfef78f67251c48fb926f1fca6a180a979e7e73e5e6111202c469150
&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&locale=en&prefetch=1&session=a129c2b323dbc9db9d6bede4b60
b6012cf41ec257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994978 302 - - 3.907 ms    
11:07:35 │ remix    │ [shopify-app/INFO] Authenticating admin request
11:07:35 │ remix    │ GET /auth/exit-iframe?embedded=1&hmac=865e706dcfef78f67251c48fb926f1fca6a180a979e7e73e5e6
111202c469150&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYmVuLWRldi12aXNp&locale=en&prefetch=1&session=a129c2b323dbc9
db9d6bede4b60b6012cf41ec257c06fdefe3f0525de715e0f7&shop=ben-dev-visi.myshopify.com&timestamp=1693994978&exitIfr
ame=%2Fauth%3Fshop%3Dben-dev-visi.myshopify.com 200 - - 2.186 ms ```

## Expected behavior

The app should install correctly and display the demo page. 

## Actual behavior

The app provides the detailed error

## Steps to reproduce the problem

1. Run `npm init @shopify/app@latest`
2. Run `npm start dev`
3. Install the application
4. Launch the application

**Comment by paulomarg** [comment]
Hi, thanks for reporting this. Looking at the logs, it seems like the callback request the app is receiving doesn't have the state cookie in it.

A few questions to help debug this:
- are you just running the app right after creating it, without making any changes?
- are you opening the app by pressing `p` while running it in the CLI?
- what browser are you using?
- do you have any extensions or settings that might be disabling cookies? Cookies are required for the app to work.

**Comment by elaser** [comment]
Hello!  Running into this issue as well:
* Running right after `npm init @shopify/app@latest`
* Yes, hitting `p` while running in CLI
* Using Chrome 117.0.5938.62 (latest version)
* Don't think so

**Comment by elaser** [comment]
Hey @paulomarg -- thanks for the response!  That seems to have solved the infinite redirect; however, running into this issue now:

```
08:42:33 │ remix │ [shopify-api/INFO] version 7.6.0, environment Remix
08:42:33 │ remix │ Remix App Server started at http://localhost:53996 
(http://192.168.1.90:53996)
08:42:34 │ remix │ Could not reach Remix dev server at 
https://church-range-time-cart.trycloudflare.com/ping
```
<img width="974" alt="Screenshot 2023-09-13 at 8 45 42 AM" src="https://github.com/Shopify/shopify-app-template-remix/assets/2738335/5538c778-7739-4dea-8cbd-02ce8203bc0b">

**Comment by paulomarg** [comment]
When you restart your app, the CLI will create a new tunnel and it needs to update your app. I believe the error you're seeing is because you may have opted not to automatically update your addresses (the CLI asks that question when you run `dev` for the first time).

You could try one of these:

- Set `automatically_update_urls_on_dev = true` in your `shopify.app.toml` file
- Run `npm run dev -- --reset` to reset the settings for your app

If neither works, can you run `npm run dev -- --verbose` and paste them here? I'll forward the information to the CLI team.

**Comment by elaser** [comment]
ah yes! my fault -- works now!! thank you so much for your patience and help!

**Comment by paulomarg** [comment]
If that's solved, then I believe this issue is now a duplicate of https://github.com/Shopify/shopify-app-template-remix/issues/286. As mentioned there, we're looking into ways to improve this flow!

**Comment by syedusama076** [comment]
@paulomarg Hey ! Hope so you are doing good.
I am facing the same issue as like @benjisoft is facing but I am facing this error on live app. I mean I deployed my app to Heroku and then install it on the store and then try to open the app but it show me the same Heroku logs as @benjisoft and then redirect to the "Settings > Apps and sales channels " and show the error "This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, [switching to another browser](https://community.shopify.com/c/Shopify-Apps/Some-Third-Party-Apps-may-not-be-accessible-on-Chrome-80-update/m-p/650220/thread-id/20503), or contacting the developer to get support."

**Comment by benjisoft** [comment]
> @paulomarg Hey ! Hope so you are doing good.
> 
> I am facing the same issue as like @benjisoft is facing but I am facing this error on live app. I mean I deployed my app to Heroku and then install it on the store and then try to open the app but it show me the same Heroku logs as @benjisoft and then redirect to the "Settings > Apps and sales channels " and show the error "This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, [switching to another browser](https://community.shopify.com/c/Shopify-Apps/Some-Third-Party-Apps-may-not-be-accessible-on-Chrome-80-update/m-p/650220/thread-id/20503), or contacting the developer to get support."

The way I resolved this was by running the commands here https://stackoverflow.com/a/77111173/6414551.

**Comment by dkcamargo** [comment]
> @paulomarg Hey ! Hope so you are doing good. I am facing the same issue as like @benjisoft is facing but I am facing this error on live app. I mean I deployed my app to Heroku and then install it on the store and then try to open the app but it show me the same Heroku logs as @benjisoft and then redirect to the "Settings > Apps and sales channels " and show the error "This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, [switching to another browser](https://community.shopify.com/c/Shopify-Apps/Some-Third-Party-Apps-may-not-be-accessible-on-Chrome-80-update/m-p/650220/thread-id/20503), or contacting the developer to get support."

Hey man i'm facing the same issue could you solve it?

**Comment by paulomarg** [comment]
Hey folks, the only case we're aware of that causes that loop is when the `config:push` command hasn't been run yet for an environment. That causes the scopes to not match the app's, and so the app thinks it needs to re-authenticate to get the right scopes, leading to the issue.

Note that for apps deployed to production, you'll also need to push the right config for your production app!

I provided a little more detail here: https://github.com/Shopify/shopify-app-template-remix/issues/286#issuecomment-1702726913

**Comment by Andrew-Golchenko** [comment]
for me the issue was solved by manually synchronizing the linux time

**Comment by DaniloArantesF** [comment]
Hey @paulomarg, I'm having the same issue described originally but none of the current solutions fixes it. My output is almost identical, it loops between authenticating and saying my shop hasn't installed the app. All I have done is clone the sample remix app following the steps [here](https://shopify.dev/docs/apps/getting-started/create). No changes were made, it never worked. As soon as I click install it starts erroring out. I have tried different browsers, uninstalling, starting over, and done the `config:link` `config:push` many times. 

![image](https://github.com/Shopify/shopify-app-template-remix/assets/33551518/412bbe60-a31e-40ce-9390-2848582a7f55)

Any clues?

**Comment by asim1048** [comment]
I have tried all the ways to solve but I am still facing same error "The app couldn’t be loaded
This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, [switching to another browser](https://community.shopify.com/c/Shopify-Apps/Some-Third-Party-Apps-may-not-be-accessible-on-Chrome-80-update/m-p/650220/thread-id/20503), or contacting the developer to get support."

**Comment by wellenzhong** [comment]
> Oh, one more thing I forgot. Could you please run the following commands:
> 
> ```shell
> npm run config:link
> npm run config:push
> npm run dev
> ```
> 
> to see if that works?

Great!
But now the `npm run config:push` same as`npm run shopify app config push` is no longer supported.use `npm run shopify app deploy` instead!
