### ISSUE TITLE
Future 'unstable_newEmbeddedAuthStrategy=true' does not work with public apps

### ISSUE THREAD

**Issue by haicaodac** [Shopify/shopify-app-template-remix#598]
# Issue summary
I have an app that is public on the Shopify App Store.
Previously we did not use the .toml file to deploy the new version. Recently we rebuilt it based on the remix template and discovered that customers could not install the app.
Cause: Previously, the app did not have an [access_scopes] section, but when adding [access_scopes] and typing yarn deploy, customers will not be able to install it and will be redirected to the apps list management.

Before opening this issue, I have:

- [x ] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
    "@shopify/app": "^3.50.0",
    "@shopify/cli": "^3.50.0",
    "@shopify/polaris": "12.16.0",
    "@shopify/shopify-api": "^9.2.0",
    "@shopify/shopify-app-remix": "^2.5.0",
    "@shopify/shopify-app-session-storage-prisma": "^3.0.0",
    "@shopify/app-bridge-react": "^3.7.9",
    "@shopify/app-bridge-types": "^0.0.3",
    
  - Node version:v18.16.0
  
  

- Case 1: If I remove the [access_scopes] in .toml and remove 'unstable_newEmbeddedAuthStrategy', the app works normally.
- Case 2: If I remove the [access_scopes] in .toml and add 'unstable_newEmbeddedAuthStrategy=true', the app cannot be installed on Shopify App Store
- Case 3: If I add [access_scopes] in .toml and add 'unstable_newEmbeddedAuthStrategy=true' then the app cannot be installed on Shopify App Store
- Case 4: If I add [access_scopes] in .toml and remove 'unstable_newEmbeddedAuthStrategy', the app cannot be installed on Shopify App Store

**Comment by haicaodac** [comment]
Bug has been fixed

**Comment by NguyenQuangHuy282002** [comment]
Hi, I'm still facing this issue. Any way to fixed? Here is my version in package.json:
    "@shopify/app": "3.53.0",
    "@shopify/cli": "3.53.0",
    "@shopify/shopify-api": "^9.7.1",
    "@shopify/shopify-app-remix": "^2.8.0",
